services:
  # broker:
  #   image: rabbitmq:4-management
  #   ports:
  #     - "5672:5672"  
  #     - "15672:15672"
  #   volumes:
  #     - rabbitmq:/var/lib/rabbitmq
  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686" # UI
      - "14268:14268"
      - "6831:6831/udp"
      - "4317:4317"
      - "4318:4318"
volumes:
  rabbitmq:
